-- Passenger airlines for the crew picker. Existing codes keep their email domains.
INSERT INTO public.airlines (code, name, icao, country_code, is_active)
VALUES
  ('CX', 'Cathay Pacific', 'CPA', 'HK', true),
  ('UO', 'HK Express', 'HKE', 'HK', true),
  ('HX', 'Hong Kong Airlines', 'CRK', 'HK', true),
  ('HB', 'Greater Bay Airlines', 'HGB', 'HK', true),
  ('JL', 'Japan Airlines', 'JAL', 'JP', true),
  ('NH', 'ANA', 'ANA', 'JP', true),
  ('ZG', 'Zipair', 'TZP', 'JP', true),
  ('MM', 'Peach', 'APJ', 'JP', true),
  ('KE', 'Korean Air', 'KAL', 'KR', true),
  ('OZ', 'Asiana Airlines', 'AAR', 'KR', true),
  ('7C', 'Jeju Air', 'JJA', 'KR', true),
  ('TW', 'T''way Air', 'TWB', 'KR', true),
  ('LJ', 'Jin Air', 'JNA', 'KR', true),
  ('CI', 'China Airlines', 'CAL', 'TW', true),
  ('BR', 'EVA Air', 'EVA', 'TW', true),
  ('JX', 'STARLUX Airlines', 'SJX', 'TW', true),
  ('IT', 'Tigerair Taiwan', 'TTW', 'TW', true),
  ('CA', 'Air China', 'CCA', 'CN', true),
  ('MU', 'China Eastern Airlines', 'CES', 'CN', true),
  ('CZ', 'China Southern Airlines', 'CSN', 'CN', true),
  ('HU', 'Hainan Airlines', 'CHH', 'CN', true),
  ('9C', 'Spring Airlines', 'CQH', 'CN', true),
  ('HO', 'Juneyao Air', 'DKH', 'CN', true),
  ('SQ', 'Singapore Airlines', 'SIA', 'SG', true),
  ('TR', 'Scoot', 'TGW', 'SG', true),
  ('TG', 'Thai Airways', 'THA', 'TH', true),
  ('PG', 'Bangkok Airways', 'BKP', 'TH', true),
  ('FD', 'Thai AirAsia', 'AIQ', 'TH', true),
  ('SL', 'Thai Lion Air', 'TLM', 'TH', true),
  ('MH', 'Malaysia Airlines', 'MAS', 'MY', true),
  ('AK', 'AirAsia', 'AXM', 'MY', true),
  ('OD', 'Batik Air Malaysia', 'MXD', 'MY', true),
  ('PR', 'Philippine Airlines', 'PAL', 'PH', true),
  ('5J', 'Cebu Pacific', 'CEB', 'PH', true),
  ('GA', 'Garuda Indonesia', 'GIA', 'ID', true),
  ('QG', 'Citilink', 'CTV', 'ID', true),
  ('JT', 'Lion Air', 'LNI', 'ID', true),
  ('VN', 'Vietnam Airlines', 'HVN', 'VN', true),
  ('VJ', 'VietJet Air', 'VJC', 'VN', true),
  ('QH', 'Bamboo Airways', 'BAV', 'VN', true),
  ('AI', 'Air India', 'AIC', 'IN', true),
  ('IX', 'Air India Express', 'AXB', 'IN', true),
  ('6E', 'IndiGo', 'IGO', 'IN', true),
  ('EK', 'Emirates', 'UAE', 'AE', true),
  ('FZ', 'flydubai', 'FDB', 'AE', true),
  ('QR', 'Qatar Airways', 'QTR', 'QA', true),
  ('EY', 'Etihad Airways', 'ETD', 'AE', true),
  ('3L', 'Air Arabia Abu Dhabi', 'ADY', 'AE', true),
  ('SV', 'Saudia', 'SVA', 'SA', true),
  ('RX', 'Riyadh Air', 'RXI', 'SA', true),
  ('XY', 'flynas', 'KNE', 'SA', true),
  ('F3', 'flyadeal', 'FAD', 'SA', true),
  ('TK', 'Turkish Airlines', 'THY', 'TR', true),
  ('PC', 'Pegasus Airlines', 'PGT', 'TR', true),
  ('VF', 'AJet', 'TKJ', 'TR', true),
  ('LY', 'El Al', 'ELY', 'IL', true),
  ('6H', 'Israir', 'ISR', 'IL', true),
  ('IZ', 'Arkia', 'AIZ', 'IL', true),
  ('BA', 'British Airways', 'BAW', 'GB', true),
  ('VS', 'Virgin Atlantic', 'VIR', 'GB', true),
  ('U2', 'easyJet', 'EZY', 'GB', true),
  ('FR', 'Ryanair', 'RYR', 'IE', true),
  ('EI', 'Aer Lingus', 'EIN', 'IE', true),
  ('AF', 'Air France', 'AFR', 'FR', true),
  ('TO', 'Transavia France', 'TVF', 'FR', true),
  ('KL', 'KLM', 'KLM', 'NL', true),
  ('HV', 'Transavia', 'TRA', 'NL', true),
  ('LH', 'Lufthansa', 'DLH', 'DE', true),
  ('EW', 'Eurowings', 'EWG', 'DE', true),
  ('DE', 'Condor', 'CFG', 'DE', true),
  ('LX', 'SWISS', 'SWR', 'CH', true),
  ('IB', 'Iberia', 'IBE', 'ES', true),
  ('I2', 'Iberia Express', 'IBS', 'ES', true),
  ('VY', 'Vueling', 'VLG', 'ES', true),
  ('AZ', 'ITA Airways', 'ITY', 'IT', true),
  ('TP', 'TAP Air Portugal', 'TAP', 'PT', true),
  ('AY', 'Finnair', 'FIN', 'FI', true),
  ('SK', 'SAS', 'SAS', 'SE', true),
  ('DY', 'Norwegian', 'NOZ', 'NO', true),
  ('LO', 'LOT Polish Airlines', 'LOT', 'PL', true),
  ('W6', 'Wizz Air', 'WZZ', 'HU', true),
  ('DL', 'Delta Air Lines', 'DAL', 'US', true),
  ('UA', 'United Airlines', 'UAL', 'US', true),
  ('AA', 'American Airlines', 'AAL', 'US', true),
  ('AS', 'Alaska Airlines', 'ASA', 'US', true),
  ('B6', 'JetBlue', 'JBU', 'US', true),
  ('WN', 'Southwest Airlines', 'SWA', 'US', true),
  ('AC', 'Air Canada', 'ACA', 'CA', true),
  ('WS', 'WestJet', 'WJA', 'CA', true),
  ('PD', 'Porter Airlines', 'POE', 'CA', true),
  ('TS', 'Air Transat', 'TSC', 'CA', true),
  ('AM', 'Aeroméxico', 'AMX', 'MX', true),
  ('Y4', 'Volaris', 'VOI', 'MX', true),
  ('VB', 'Viva Aerobus', 'VIV', 'MX', true),
  ('LA', 'LATAM Airlines', 'LAN', 'CL', true),
  ('JJ', 'LATAM Brasil', 'TAM', 'BR', true),
  ('LP', 'LATAM Peru', 'LPE', 'PE', true),
  ('G3', 'GOL', 'GLO', 'BR', true),
  ('AD', 'Azul', 'AZU', 'BR', true),
  ('H2', 'Sky Airline', 'SKU', 'CL', true),
  ('JA', 'JetSMART', 'JAT', 'CL', true),
  ('AV', 'Avianca', 'AVA', 'CO', true),
  ('CM', 'Copa Airlines', 'CMP', 'PA', true),
  ('AR', 'Aerolíneas Argentinas', 'ARG', 'AR', true),
  ('FO', 'Flybondi', 'FBZ', 'AR', true),
  ('ET', 'Ethiopian Airlines', 'ETH', 'ET', true),
  ('SA', 'South African Airways', 'SAA', 'ZA', true),
  ('FA', 'FlySafair', 'SFR', 'ZA', true),
  ('4Z', 'Airlink', 'LNK', 'ZA', true),
  ('KQ', 'Kenya Airways', 'KQA', 'KE', true),
  ('JM', 'Jambojet', 'JMA', 'KE', true),
  ('AT', 'Royal Air Maroc', 'RAM', 'MA', true),
  ('MS', 'EgyptAir', 'MSR', 'EG', true),
  ('P4', 'Air Peace', 'APK', 'NG', true),
  ('QF', 'Qantas', 'QFA', 'AU', true),
  ('JQ', 'Jetstar', 'JST', 'AU', true),
  ('VA', 'Virgin Australia', 'VOZ', 'AU', true),
  ('NZ', 'Air New Zealand', 'ANZ', 'NZ', true),
  ('FJ', 'Fiji Airways', 'FJI', 'FJ', true)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  icao = EXCLUDED.icao,
  country_code = EXCLUDED.country_code,
  is_active = true;
