// GENERATED by crew-up-nhost/scripts/sync-shared.mjs from packages/shared/src. Do not edit; run `npm run sync:shared`.
import { z } from 'zod';
import { COUNTRY_CODES } from '../reference/countries.js';
import { LANGUAGE_CODES } from '../reference/languages.js';
import { isReservedUsername } from '../reference/reservedUsernames.js';
import { APP_MODES, CREW_ROLES, ONBOARDING_STEPS, type OnboardingStep } from '../onboarding/steps.js';

export const AppModeSchema = z.enum(APP_MODES);
export const AppConfigSchema = z.object({ mode: AppModeSchema });
export type AppConfig = z.infer<typeof AppConfigSchema>;

export const MINIMUM_AGE = 18;
export const MAXIMUM_AGE = 100;

const collapseWhitespace = (value: string) => value.trim().replace(/\s+/g, ' ');

/** Unicode letters and marks, spaces, `-`, `'`, `.`; must start with a letter. Single-token names allowed. */
export const FULL_NAME_PATTERN = /^[\p{L}\p{M}][\p{L}\p{M} .'’-]*$/u;
export const USERNAME_PATTERN = /^[a-z][a-z0-9._]*$/;

const optionalText = (max: number) =>
  z
    .string()
    .overwrite(collapseWhitespace)
    .max(max)
    .nullish()
    .transform((value) => (value ? value : null));

export const FullNameSchema = z
  .string()
  .overwrite(collapseWhitespace)
  .min(2, 'Enter your full name')
  .max(100)
  .regex(FULL_NAME_PATTERN, 'Use letters, spaces, hyphens, apostrophes or dots only');

export const UsernameSchema = z
  .string()
  .trim()
  .toLowerCase()
  .min(3, 'At least 3 characters')
  .max(20, 'At most 20 characters')
  .regex(USERNAME_PATTERN, 'Start with a letter; use a–z, 0–9, "." or "_"')
  .refine((value) => !/[._]{2}/.test(value), 'No consecutive "." or "_"')
  .refine((value) => !isReservedUsername(value), 'This username is reserved');

const CountryCodeSchema = z
  .string()
  .trim()
  .toUpperCase()
  .refine((value) => COUNTRY_CODES.has(value), 'Choose a country');

/** Whole years between an ISO date (YYYY-MM-DD) and `today`. */
export function ageOn(dateOfBirth: string, today: Date = new Date()): number {
  const [year, month, day] = dateOfBirth.split('-').map(Number);
  let age = today.getUTCFullYear() - year;
  const beforeBirthday =
    today.getUTCMonth() + 1 < month || (today.getUTCMonth() + 1 === month && today.getUTCDate() < day);
  if (beforeBirthday) age -= 1;
  return age;
}

function isRealDate(value: string): boolean {
  const date = new Date(`${value}T00:00:00Z`);
  return !Number.isNaN(date.getTime()) && date.toISOString().slice(0, 10) === value;
}

export const DateOfBirthSchema = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}$/, 'Use YYYY-MM-DD')
  .refine(isRealDate, 'Enter a valid date')
  .refine((value) => ageOn(value) >= MINIMUM_AGE, `You must be ${MINIMUM_AGE} or older to join CrewUp`)
  .refine((value) => ageOn(value) <= MAXIMUM_AGE, 'Enter a valid date');

export const NameHandleSchema = z.object({
  fullName: FullNameSchema,
  fullNameNative: optionalText(100),
  preferredName: optionalText(50),
  username: UsernameSchema,
});

export const AboutSchema = z.object({
  dateOfBirth: DateOfBirthSchema,
  homeCountryCode: CountryCodeSchema,
  hometownCity: optionalText(100),
  languages: z
    .array(z.string().refine((code) => LANGUAGE_CODES.has(code), 'Unsupported language'))
    .min(1, 'Choose at least one language')
    .max(10),
});

export const ResidenceSchema = z.object({
  residenceCountryCode: CountryCodeSchema,
  residenceCity: z
    .string()
    .overwrite(collapseWhitespace)
    .min(1, 'Enter your city')
    .max(100)
    .regex(/^[^\d@#]+$/, 'City only — no street address'),
});

export const CrewIdentitySchema = z.object({
  crewRole: z.enum(CREW_ROLES),
  airlineId: z.guid('Choose your airline'),
  baseAirportIata: z
    .string()
    .trim()
    .toUpperCase()
    .regex(/^[A-Z]{3}$/, 'Choose your base airport'),
});

export const PHONE_E164_PATTERN = /^\+[1-9]\d{6,14}$/;

export const PhoneSchema = z.object({
  phoneE164: z.string().regex(PHONE_E164_PATTERN, 'Enter a valid phone number').nullish(),
});

export const PhotoSchema = z.object({
  avatarFileId: z.guid().nullish(),
});

const EmptySchema = z.object({}).strip();

export const ProfileCompleteSchema = z.object({
  ...NameHandleSchema.shape,
  ...AboutSchema.shape,
  ...ResidenceSchema.shape,
  ...CrewIdentitySchema.shape,
});

export const STEP_SCHEMAS = {
  name_handle: NameHandleSchema,
  about: AboutSchema,
  residence: ResidenceSchema,
  crew: CrewIdentitySchema,
  phone: PhoneSchema,
  photo: PhotoSchema,
  review: EmptySchema,
  beta_notify: EmptySchema,
  launch_privacy: EmptySchema,
  launch_guidelines: EmptySchema,
  launch_notifications: EmptySchema,
} as const satisfies Record<OnboardingStep, z.ZodType>;

export type StepInput<S extends OnboardingStep> = z.input<(typeof STEP_SCHEMAS)[S]>;
export type StepData<S extends OnboardingStep> = z.output<(typeof STEP_SCHEMAS)[S]>;
export type ProfileComplete = z.output<typeof ProfileCompleteSchema>;

/** Body of `PUT /onboarding/step`. `data` is validated separately with `STEP_SCHEMAS[step]`. */
export const StepRequestSchema = z.object({
  step: z.enum(ONBOARDING_STEPS),
  data: z.record(z.string(), z.unknown()).default({}),
  /** Edit profile saves reuse step validation without moving `current_step`. */
  advance: z.boolean().default(true),
});

export const CompleteRequestSchema = z.object({
  guidelinesVersion: z.string().min(1),
});

export const UsernameAvailabilityQuerySchema = z.object({ u: z.string().max(64) });
