// GENERATED by crew-up-nhost/scripts/sync-shared.mjs from packages/shared/src. Do not edit; run `npm run sync:shared`.
const RESERVED = new Set([
  'admin', 'administrator', 'root', 'system', 'staff', 'support', 'help', 'helpdesk', 'moderator', 'mod',
  'official', 'security', 'safety', 'trust', 'team', 'info', 'contact', 'billing', 'legal', 'privacy',
  'api', 'www', 'app', 'mail', 'email', 'noreply', 'null', 'undefined', 'anonymous', 'everyone', 'me',
  'crewup', 'crew', 'crews', 'pilot', 'captain', 'cabincrew',
  // Airline brands (IATA-listed carriers served by CrewUp and major global carriers).
  'cathay', 'cathaypacific', 'hkexpress', 'hongkongairlines', 'greaterbay', 'singaporeair', 'singaporeairlines',
  'scoot', 'emirates', 'qatar', 'qatarairways', 'etihad', 'jal', 'japanairlines', 'ana', 'allnippon',
  'koreanair', 'asiana', 'evaair', 'chinaairlines', 'starlux', 'airchina', 'chinaeastern', 'chinasouthern',
  'thaiairways', 'vietnamairlines', 'garuda', 'malaysiaairlines', 'airasia', 'philippineairlines',
  'cebupacific', 'qantas', 'jetstar', 'airnewzealand', 'lufthansa', 'britishairways', 'airfrance', 'klm',
  'turkishairlines', 'united', 'delta', 'americanairlines', 'aircanada',
]);

/** Reserved handles, plus anything that impersonates the brand ("crewup_help", "crewupofficial"). */
export function isReservedUsername(username: string): boolean {
  const normalized = username.toLowerCase();
  if (RESERVED.has(normalized)) return true;
  if (normalized.startsWith('crewup')) return true;
  return RESERVED.has(normalized.replace(/[._]/g, ''));
}
