#!/usr/bin/env node
/**
 * Copies ../packages/shared/src into functions/_shared so Nhost deploys stay self-contained.
 * Relative imports are rewritten to `./x.js` (NodeNext output). Run with `--check` in CI to fail
 * when the committed copy is stale.
 */
import { readdir, readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const sourceRoot = path.resolve(here, '../../packages/shared/src');
const targetRoot = path.resolve(here, '../functions/_shared');
const checkOnly = process.argv.includes('--check');

const HEADER =
  '// GENERATED by crew-up-nhost/scripts/sync-shared.mjs from packages/shared/src. Do not edit; run `npm run sync:shared`.\n';

async function listFiles(dir, base = dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await listFiles(full, base)));
    else if (entry.name.endsWith('.ts')) files.push(path.relative(base, full));
  }
  return files.sort();
}

function transform(source) {
  const rewritten = source.replace(
    /(from\s+|import\s*\(\s*)(['"])(\.{1,2}\/[^'"]+?)\2/g,
    (match, prefix, quote, specifier) =>
      /\.[cm]?[jt]s$/.test(specifier) ? match : `${prefix}${quote}${specifier}.js${quote}`,
  );
  return HEADER + rewritten;
}

if (!existsSync(sourceRoot)) {
  console.error(`sync-shared: source not found at ${sourceRoot}`);
  process.exit(1);
}

const sourceFiles = await listFiles(sourceRoot);
const expected = new Map();
for (const file of sourceFiles) {
  expected.set(file, transform(await readFile(path.join(sourceRoot, file), 'utf8')));
}

if (checkOnly) {
  const actualFiles = existsSync(targetRoot) ? await listFiles(targetRoot) : [];
  const stale = [];
  for (const [file, contents] of expected) {
    const target = path.join(targetRoot, file);
    if (!existsSync(target) || (await readFile(target, 'utf8')) !== contents) stale.push(file);
  }
  for (const file of actualFiles) if (!expected.has(file)) stale.push(`${file} (extra)`);
  if (stale.length) {
    console.error(`functions/_shared is out of date:\n  ${stale.join('\n  ')}\nRun: npm run sync:shared`);
    process.exit(1);
  }
  console.log('functions/_shared is up to date.');
} else {
  await rm(targetRoot, { recursive: true, force: true });
  for (const [file, contents] of expected) {
    const target = path.join(targetRoot, file);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, contents);
  }
  console.log(`Synced ${expected.size} files into functions/_shared.`);
}
