// GENERATED by crew-up-nhost/scripts/sync-shared.mjs from packages/shared/src. Do not edit; run `npm run sync:shared`.
import {
  PROFILE_STEPS,
  isBetaStep,
  isLaunchStep,
  isProfileStep,
  type AppMode,
  type OnboardingStep,
} from './steps.js';

/** The subset of `onboarding_state` the router needs. `null` = no row yet. */
export type OnboardingSnapshot = {
  currentStep: string | null;
  betaSignupCompletedAt: string | null;
  onboardingCompletedAt: string | null;
} | null;

export type EntryRoute =
  | { kind: 'main' }
  | { kind: 'beta_holding' }
  | { kind: 'mode_unavailable' }
  | {
      kind: 'onboarding';
      variant: 'beta' | 'fresh' | 'prefilled_from_beta';
      step: OnboardingStep;
    };

const FIRST_STEP: OnboardingStep = PROFILE_STEPS[0];

/**
 * Onboarding entry routing (onboarding.md §3.1). Pure: mode + two timestamps + resume step.
 * `mode === null` means app-config could not be fetched and nothing is cached; never assume "launched".
 */
export function resolveEntryRoute(mode: AppMode | null, state: OnboardingSnapshot): EntryRoute {
  if (state?.onboardingCompletedAt) return { kind: 'main' };
  if (mode === null) return { kind: 'mode_unavailable' };

  const current = state?.currentStep ?? null;

  if (mode === 'beta') {
    if (state?.betaSignupCompletedAt) return { kind: 'beta_holding' };
    const step: OnboardingStep =
      isProfileStep(current) || isBetaStep(current) ? current : isLaunchStep(current) ? 'review' : FIRST_STEP;
    return { kind: 'onboarding', variant: 'beta', step };
  }

  if (state?.betaSignupCompletedAt) {
    return {
      kind: 'onboarding',
      variant: 'prefilled_from_beta',
      step: isLaunchStep(current) ? current : 'review',
    };
  }

  const step: OnboardingStep =
    isProfileStep(current) || isLaunchStep(current) ? current : isBetaStep(current) ? 'review' : FIRST_STEP;
  return { kind: 'onboarding', variant: 'fresh', step };
}
