// GENERATED by crew-up-nhost/scripts/sync-shared.mjs from packages/shared/src. Do not edit; run `npm run sync:shared`.
export const APP_MODES = ['beta', 'launched'] as const;
export type AppMode = (typeof APP_MODES)[number];

/** Bump when steps are added, removed or reordered so clients can handle older in-progress states. */
export const FLOW_VERSION = 1;

/** Version string stored in `onboarding_state.guidelines_accepted_version`. */
export const GUIDELINES_VERSION = '2026-09';

/** Steps 1–7, shared by beta sign-up and standard onboarding. */
export const PROFILE_STEPS = [
  'name_handle',
  'about',
  'residence',
  'crew',
  'phone',
  'photo',
  'review',
] as const;
export type ProfileStep = (typeof PROFILE_STEPS)[number];

export const BETA_STEPS = ['beta_notify'] as const;
export type BetaStep = (typeof BETA_STEPS)[number];

export const LAUNCH_STEPS = ['launch_privacy', 'launch_guidelines', 'launch_notifications'] as const;
export type LaunchStep = (typeof LAUNCH_STEPS)[number];

export const ONBOARDING_STEPS = [...PROFILE_STEPS, ...BETA_STEPS, ...LAUNCH_STEPS] as const;
export type OnboardingStep = (typeof ONBOARDING_STEPS)[number];

/** Steps the user may skip with "Skip for now". */
export const SKIPPABLE_STEPS: readonly OnboardingStep[] = ['phone', 'photo', 'beta_notify'];

export const CREW_ROLES = ['cabin_crew', 'pilot', 'ground_ops', 'other'] as const;
export type CrewRole = (typeof CREW_ROLES)[number];

export function isOnboardingStep(value: unknown): value is OnboardingStep {
  return typeof value === 'string' && (ONBOARDING_STEPS as readonly string[]).includes(value);
}

export function isProfileStep(value: unknown): value is ProfileStep {
  return typeof value === 'string' && (PROFILE_STEPS as readonly string[]).includes(value);
}

export function isLaunchStep(value: unknown): value is LaunchStep {
  return typeof value === 'string' && (LAUNCH_STEPS as readonly string[]).includes(value);
}

export function isBetaStep(value: unknown): value is BetaStep {
  return typeof value === 'string' && (BETA_STEPS as readonly string[]).includes(value);
}

/** Ordered steps for a mode: profile steps, then that mode's ending. */
export function stepsForMode(mode: AppMode): readonly OnboardingStep[] {
  return mode === 'beta' ? [...PROFILE_STEPS, ...BETA_STEPS] : [...PROFILE_STEPS, ...LAUNCH_STEPS];
}

/** Next step in the mode's sequence, or null after the last step (call beta-complete / complete). */
export function nextStep(mode: AppMode, step: OnboardingStep): OnboardingStep | null {
  const steps = stepsForMode(mode);
  const index = steps.indexOf(step);
  if (index === -1) return steps[0] ?? null;
  return steps[index + 1] ?? null;
}

export function previousStep(mode: AppMode, step: OnboardingStep): OnboardingStep | null {
  const steps = stepsForMode(mode);
  const index = steps.indexOf(step);
  return index > 0 ? steps[index - 1] : null;
}
